[package]
authors = ["Fraser Hutchison <fraser.hutchison@maidsafe.net>"]
categories = ["command-line-utilities", "development-tools"]
description = "An interactive CLI tool to add a remote fork to a local Git repository."
documentation = "https://docs.rs/add-remote"
keywords = ["git", "github"]
license = "MIT/Apache-2.0"
name = "add-remote"
readme = "README.md"
repository = "https://github.com/Fraser999/Add-Remote.git"
version = "0.9.0"

[dependencies]
colour = "0.2"
ctrlc = "3.0"
find_git = "1.1"
reqwest = "0.7"
serde_json = "1.0"
unwrap = "1.1"
