[package]
authors = ["Fraser Hutchison <fraser.hutchison@maidsafe.net>"]
description = "An interactive CLI tool to add a remote fork to a local Git repository."
license = "GPL-3.0"
name = "add-remote"
readme = "README.md"
version = "0.8.0"

[dependencies]
colour = "0.2"
ctrlc = "3.0"
find_git = "1.1"
reqwest = "0.6"
serde_json = "1.0"
unwrap = "1.1"
