array_layout = "Visual"
combine_control_expr = false
condense_wildcard_suffices = true
control_style = "Legacy"
fn_args_layout = "Visual"
fn_args_paren_newline = true
fn_call_style = "Visual"
fn_call_width = 100
fn_single_line = true
generics_indent = "Visual"
ideal_width = 100
newline_style = "Native"
reorder_imports = true
reorder_imported_names = true
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
use_try_shorthand = true
where_style = "Legacy"
write_mode = "Overwrite"
